name: 'Early Access POC Action'
description: 'Creates a process around to enable early-access programs for trials'
inputs:
  github-token:  # id of input
    description: 'Token to use'
    required: true
outputs:
runs:
  using: 'node12'
  main: 'index.js'