name: 'Early Access POC Action'
description: 'Creates a process around to enable early-access programs for trials'
inputs:
  github-token:  # id of input
    description: 'Token to use'
    required: true
  requestedLabelID:  
    description: 'Label ID for security-center-requested label'
    required: true
  requestedIssueID:
      description: 'Issue ID to post requests'
      required: true
runs:
  using: 'node12'
  main: 'index.js'